apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: hub-deployment
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: jupyterhub
        service: jupyterhub
    spec:
      volumes:
      - name: config
        configMap:
          name: hub-config
      - name: secret
        secret:
          secretName: hub-secret
      - name: hub-db-dir
        persistentVolumeClaim:
          claimName: hub-db-dir
      serviceAccountName: jupyterhub
      containers:
 
      - name: hub-container
        image: jupyterhub/k8s-hub:v0.4
        volumeMounts:
          - mountPath: /etc/jupyterhub/config/
            name: config
          - mountPath: /etc/jupyterhub/secret/
            name: secret
          - mountPath: /srv/jupyterhub/
            name: hub-db-dir
        imagePullPolicy: IfNotPresent
        env:
        - name: SINGLEUSER_IMAGE
          value: jupyterhub/k8s-singleuser-sample:v0.4
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: CONFIGPROXY_AUTH_TOKEN
          valueFrom:
            secretKeyRef:
              name: hub-secret
              key: proxy.token

      - name: proxy-container
        image: jupyterhub/configurable-http-proxy:2.0.4
        command:
        - configurable-http-proxy
        - --ip=127.0.0.1
        - --port=8000
        - --api-ip=127.0.0.1
        - --api-port=8001
        - --default-target=http://127.0.0.1:8000
        - --error-target=http://127.0.0.1:8000/hub/error
        - --log-level=debug
        env:
          - name: CONFIGPROXY_AUTH_TOKEN
            valueFrom:
              secretKeyRef:
                name: hub-secret
                key: proxy.token
        imagePullPolicy: IfNotPresent
        ports:
          - containerPort: 8000
            name: proxy-public
          - containerPort: 8001
            name: api
