
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: proxy-deployment
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: proxy-pod
    spec:
      containers:
      - name: proxy-container
        image: jupyterhub/configurable-http-proxy:2.0.4
        command:
        - configurable-http-proxy
        - --ip=0.0.0.0
        - --port=8000
        - --api-ip=0.0.0.0
        - --api-port=8001
        - --default-target=http://$(HUB_SERVICE_HOST):$(HUB_SERVICE_PORT)
        - --error-target=http://$(HUB_SERVICE_HOST):$(HUB_SERVICE_PORT)
        - --log-level=debug
        resources:
          requests:
            cpu: 0.2
            memory: 512Mi
        env:
          - name: CONFIGPROXY_AUTH_TOKEN
            valueFrom:
              secretKeyRef:
                name: hub-secret
                key: proxy.token
        imagePullPolicy: IfNotPresent
        ports:
          - containerPort: 8000
            name: proxy-public
          - containerPort: 8001
            name: api
